#!/bin/sh
# This file is a modified copy of src/scripts/sc4pac for testing purposes.
#
# Invocation of sc4pac command-line interface on Linux or macOS.
# In a terminal, call:
#
#     ./sc4pac


SCRIPTDIR="${0%/*}"

# We set defaults for environment variables if they are not defined.
# The environment variable `SC4PAC_MONO_CMD` is only needed on Linux and macOS.
# If you happen to run this script on Windows without Mono installed, remove the environment variable.
export SC4PAC_MONO_CMD="${SC4PAC_MONO_CMD-"mono"}"
export SC4PAC_CICDEC_CMD="${SC4PAC_CICDEC_CMD-"${SCRIPTDIR}/cicdec/cicdec.exe"}"

java -jar "${SCRIPTDIR}/target/scala-3.4.2/sc4pac-cli.jar" "$@"
